export const authConstant = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILUER: "LOGIN_FAILUER",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILUER: "LOGOUT_FAILUER",
};

export const userConstant = {
  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILUER: "USER_REGISTER_FAILUER",
};

export const categoryConstant = {
  GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILUER: "GET_ALL_CATEGORIES_FAILUER",
  ADD_NEW_CATEGORY_REQUEST: "ADD_NEW_CATEGORY_REQUEST",
  ADD_NEW_CATEGORY_SUCCESS: "ADD_NEW_CATEGORY_SUCCESS",
  ADD_NEW_CATEGORY_FAILUER: "ADD_NEW_CATEGORY_FAILUER",
};

export const productConstant = {
  GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILUER: "GET_ALL_PRODUCTS_FAILUER",
  ADD_NEW_PRODUCT_REQUEST: "ADD_NEW_PRODUCT_REQUEST",
  ADD_NEW_PRODUCT_SUCCESS: "ADD_NEW_PRODUCT_SUCCESS",
  ADD_NEW_PRODUCT_FAILUER: "ADD_NEW_PRODUCT_FAILUER",
};

export const initialDataConstant = {
  GET_INITILADATA_REQUEST: "GET_INITILADATA_REQUEST",
  GET_INITILADATA_SUCCESS: "GET_INITILADATA_SUCCESS",
  GET_INITILADATA_FAILUER: "GET_INITILADATA_FAILUER",
};
